services:
  weatherflow-collector-local-udp-influxdb:
    container_name: weatherflow-collector-local-udp-influxdb
    environment:
      WEATHERFLOW_COLLECTOR_BACKEND_TYPE: influxdb
      WEATHERFLOW_COLLECTOR_COLLECTOR_TYPE: local-udp
      WEATHERFLOW_COLLECTOR_DEBUG: "false"
      WEATHERFLOW_COLLECTOR_INFLUXDB_PASSWORD: <<PASSWORD>>
      WEATHERFLOW_COLLECTOR_INFLUXDB_URL: http://influxdb:8086/write?db=weatherflow
      WEATHERFLOW_COLLECTOR_INFLUXDB_USERNAME: <<USERNAME>>
    image: lux4rd0/weatherflow-collector:2.1.4
    ports:
    - protocol: udp
      published: 50222
      target: 50222
    restart: always
  weatherflow-collector-remote-rest-influxdb:
    container_name: weatherflow-collector-remote-rest-influxdb
    environment:
      WEATHERFLOW_COLLECTOR_BACKEND_TYPE: influxdb
      WEATHERFLOW_COLLECTOR_COLLECTOR_TYPE: remote-rest
      WEATHERFLOW_COLLECTOR_DEBUG: "false"
      WEATHERFLOW_COLLECTOR_INFLUXDB_PASSWORD: <<PASSWORD>>
      WEATHERFLOW_COLLECTOR_INFLUXDB_URL: http://influxdb:8086/write?db=weatherflow
      WEATHERFLOW_COLLECTOR_INFLUXDB_USERNAME: <<USERNAME>>
      WEATHERFLOW_COLLECTOR_REMOTE_COLLECTOR_DEVICE_ID: <<DEVICE_ID>>
      WEATHERFLOW_COLLECTOR_REMOTE_COLLECTOR_STATION_ID: <<STATION_ID>>
      WEATHERFLOW_COLLECTOR_REMOTE_COLLECTOR_TOKEN: <<TOKEN>>
      WEATHERFLOW_COLLECTOR_REMOTE_REST_INTERVAL: 60
    image: lux4rd0/weatherflow-collector:2.1.4
    restart: always
  weatherflow-collector-remote-socket-influxdb:
    container_name: weatherflow-collector-remote-socket-influxdb
    environment:
      WEATHERFLOW_COLLECTOR_BACKEND_TYPE: influxdb
      WEATHERFLOW_COLLECTOR_COLLECTOR_TYPE: remote-socket
      WEATHERFLOW_COLLECTOR_DEBUG: "false"
      WEATHERFLOW_COLLECTOR_INFLUXDB_PASSWORD: <<PASSWORD>>
      WEATHERFLOW_COLLECTOR_INFLUXDB_URL: http://influxdb:8086/write?db=weatherflow
      WEATHERFLOW_COLLECTOR_INFLUXDB_USERNAME: <<USERNAME>>
      WEATHERFLOW_COLLECTOR_REMOTE_COLLECTOR_DEVICE_ID: <<DEVICE_ID>>
      WEATHERFLOW_COLLECTOR_REMOTE_COLLECTOR_STATION_ID: <<STATION_ID>>
      WEATHERFLOW_COLLECTOR_REMOTE_COLLECTOR_TOKEN: <<TOKEN>>
    image: lux4rd0/weatherflow-collector:2.1.4
    restart: always
  weatherflow-collector-remote-forecast-influxdb:
    container_name: weatherflow-collector-remote-forecast-influxdb
    environment:
      WEATHERFLOW_COLLECTOR_BACKEND_TYPE: influxdb
      WEATHERFLOW_COLLECTOR_COLLECTOR_TYPE: remote-forecast
      WEATHERFLOW_COLLECTOR_DEBUG: "false"
      WEATHERFLOW_COLLECTOR_INFLUXDB_PASSWORD: <<PASSWORD>>
      WEATHERFLOW_COLLECTOR_INFLUXDB_URL: http://influxdb:8086/write?db=weatherflow
      WEATHERFLOW_COLLECTOR_INFLUXDB_USERNAME: influxdb
      WEATHERFLOW_COLLECTOR_REMOTE_COLLECTOR_STATION_ID: <<STATION_ID>>
      WEATHERFLOW_COLLECTOR_REMOTE_COLLECTOR_TOKEN: <<TOKEN>>
      WEATHERFLOW_COLLECTOR_HOST_HOSTNAME: ${WEATHERFLOW_COLLECTOR_HOST_HOSTNAME}
      WEATHERFLOW_COLLECTOR_REMOTE_FORECAST_INTERVAL: 60
    image: lux4rd0/weatherflow-collector:2.1.4
    logging:
      driver: loki
      options:
        loki-url: http://log01.tylephony.com:3100/loki/api/v1/push
    restart: always
version: '3.8'
