services:
  weatherflow-listener-local-udp-influxdb:
    container_name: weatherflow-listener-local-udp-influxdb
    environment:
      WEATHERFLOW_LISTENER_BACKEND_TYPE: influxdb
      WEATHERFLOW_LISTENER_COLLECTOR_TYPE: local-udp
      WEATHERFLOW_LISTENER_DEBUG: "false"
      WEATHERFLOW_LISTENER_INFLUXDB_PASSWORD: <<PASSWORD>>
      WEATHERFLOW_LISTENER_INFLUXDB_URL: http://influxdb:8086/write?db=weatherflow
      WEATHERFLOW_LISTENER_INFLUXDB_USERNAME: <<USERNAME>>
    image: lux4rd0/weatherflow-listener:2.0.0
    ports:
    - protocol: udp
      published: 50222
      target: 50222
    restart: always
  weatherflow-listener-remote-rest-influxdb:
    container_name: weatherflow-listener-remote-rest-influxdb
    environment:
      WEATHERFLOW_LISTENER_BACKEND_TYPE: influxdb
      WEATHERFLOW_LISTENER_COLLECTOR_TYPE: remote-rest
      WEATHERFLOW_LISTENER_DEBUG: "false"
      WEATHERFLOW_LISTENER_INFLUXDB_PASSWORD: <<PASSWORD>>
      WEATHERFLOW_LISTENER_INFLUXDB_URL: http://influxdb:8086/write?db=weatherflow
      WEATHERFLOW_LISTENER_INFLUXDB_USERNAME: <<USERNAME>>
      WEATHERFLOW_LISTENER_REMOTE_COLLECTOR_DEVICE_ID: <<DEVICE_ID>>
      WEATHERFLOW_LISTENER_REMOTE_COLLECTOR_STATION_ID: <<STATION_ID>>
      WEATHERFLOW_LISTENER_REMOTE_COLLECTOR_TOKEN: <<TOKEN>>
    image: lux4rd0/weatherflow-listener:2.0.0
    restart: always
  weatherflow-listener-remote-socket-influxdb:
    container_name: weatherflow-listener-remote-socket-influxdb
    environment:
      WEATHERFLOW_LISTENER_BACKEND_TYPE: influxdb
      WEATHERFLOW_LISTENER_COLLECTOR_TYPE: remote-socket
      WEATHERFLOW_LISTENER_DEBUG: "false"
      WEATHERFLOW_LISTENER_INFLUXDB_PASSWORD: <<PASSWORD>>
      WEATHERFLOW_LISTENER_INFLUXDB_URL: http://influxdb:8086/write?db=weatherflow
      WEATHERFLOW_LISTENER_INFLUXDB_USERNAME: <<USERNAME>>
      WEATHERFLOW_LISTENER_REMOTE_COLLECTOR_DEVICE_ID: <<DEVICE_ID>>
      WEATHERFLOW_LISTENER_REMOTE_COLLECTOR_STATION_ID: <<STATION_ID>>
      WEATHERFLOW_LISTENER_REMOTE_COLLECTOR_TOKEN: <<TOKEN>>
    image: lux4rd0/weatherflow-listener:2.0.0
    restart: always
version: '3.8'
